insert into productos(nombre,precio,create_at) values('vortex',65,Now());
insert into productos(nombre,precio,create_at) values('gsxs750',180,Now());
insert into productos(nombre,precio,create_at) values('fz250',39,Now());
insert into productos(nombre,precio,create_at) values('ktm790',210,Now());
insert into productos(nombre,precio,create_at) values('ninja650',190,Now());
insert into productos(nombre,precio,create_at) values('cbr650',188,Now());
insert into productos(nombre,precio,create_at) values('duke290',79,Now());
insert into productos(nombre,precio,create_at) values('mt09',225,Now());
insert into productos(nombre,precio,create_at) values('z900',215,Now());